version: '3.7'
services:
  jenkins:
    container_name: "devops-jenkins"
    # image: jenkins/jenkins:lts
    build:
        context: ./jenkins
        dockerfile: Dockerfile
    volumes:
      - jenkins-volume:/var/jenkins_home:rw
    ports:
      - "7777:8080"
      - "60000:50000"
    networks:
      - devops-network

  ansible:
    # image: ansible/ansible:ubuntu1404
    container_name: "devops-ansible"
    # network_mode: host
    build:
        context: ./ansible
        dockerfile: Dockerfile
    volumes:
      - ansible-volume:/ansible:rw
      - ./ansible/test:/test
    networks:
      - devops-network
    ports:
      - "7022:22"
    command: /bin/sh -c "while sleep 1000; do :; done"


  # The backend MySQL database server.
  #
  # This is accessed directly by Review Board.
  #
  # In production, this should be shared across all Review Board instances.
  db:
    container_name: "devops-reviewboard-database"
    image: mysql:8
    environment:
      # The name of the MySQL database storing Review Board content.
      - MYSQL_DATABASE=reviewboard

      # The MySQL username for Review Board.
      - MYSQL_USER=reviewboard

      # The MySQL password for Review Board.
      #
      # CHANGEME: Use a strong password!
      - MYSQL_PASSWORD=reviewboard123

      # - MYSQL_PORT=9999
      # - MYSQL_HOST=db

      # The root MySQL password.
      #
      # CHANGEME: Use a strong password!
      - MYSQL_ROOT_PASSWORD=admin123

    volumes:
      - reviewboard-database-volume:/var/lib/mysql:rw

    restart: 'on-failure'
    networks:
      - devops-network


  # The backend memory caching server.
  #
  # This is accessed directly by Review Board.
  #
  # In production, this should be shared across all Review Board instances,
  # and should be configured with at least 2GB of RAM.
  memcached:
    container_name: "devops-reviewboard-cache"
    image: memcached:alpine
    restart: 'on-failure'

    entrypoint:
      - memcached

      # The amount of RAM available for memcached.
      #
      # CHANGEME: Set this to a suitable amount for your server. We recommend
      #           at least 2GB in production (2048).
      - -m 128
    networks:
      - devops-network


  # The backend Review Board server.
  #
  # This should not be accessed directly. Instead, please access the frontend
  # nginx server.
  reviewboard:
    container_name: "devops-reviewboard"
    image: beanbag/reviewboard:6.0b1
    depends_on:
      - db
      - memcached
    environment:
      - DATABASE_TYPE=mysql
      # - DATABASE_NAME=reviewboard
      # - DATABASE_USER=root
      # - DATABASE_PASSWORD=password
      # - DATABASE_HOST=db
      # - DATABASE_PORT=9999

      # The name of your company.
      #
      # CHANGEME: You should use your actual name here. It's used for
      #           internal state and your in-app support page.
      - COMPANY=Govind's DevOps Kit

      # CHANGEME: Set this to the database username above.
      - DATABASE_USERNAME=reviewboard

      # CHANGEME: Set this to the database password above.
      - DATABASE_PASSWORD=reviewboard123

      # CHANGEME: Set this to your accessible domain name.
      - DOMAIN=localhost

    volumes:
      - reviewboard-site-volume:/site
    networks:
      - devops-network

  # The frontend nginx web server.
  #
  # This serves up static media (CSS, JavaScript, and images), and forwards
  # all other requests to the Review Board backend server.
  #
  # This is the server you will access for Review Board.
  reviewboard-frontend-server:
    container_name: "devops-reviewboard-frontend-server"
    image: nginx:alpine
    restart: always
    depends_on:
      - reviewboard

    environment:
      # CHANGEME: Set this to your accessible domain name above.
      - NGINX_HOST=localhost

      # The public port used to access this instance.
      #
      # If changed, you will need to change 'ports' below to match.
      - NGINX_PORT=80

    ports:
      - 8889:80

    volumes:
      - reviewboard-site-volume:/var/www/reviewboard
      - ./reviewboard/nginx/templates:/etc/nginx/templates
    networks:
      - devops-network

volumes:
  jenkins-volume:
    driver: local
    driver_opts: { o: bind, type: none, device: ./jenkins/volume-data }
  reviewboard-database-volume:
    driver: local
    driver_opts: { o: bind, type: none, device: ./reviewboard/volume-data }
  reviewboard-site-volume:
    driver: local
    driver_opts: { o: bind, type: none, device: ./reviewboard/site }
  ansible-volume:
    driver: local
    driver_opts: { o: bind, type: none, device: ./ansible/volume-data }

networks:
  devops-network:
    driver: bridge